version: '3'

services:
  web:
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports: 
#       - "3000:3000"
#     volumes:
#       - /app/node_modules
#       - .:/app
#     environment:
#       - NODE_ENV=development